generic_specific/urls.py
from django.contrib import admin
from django.urls import path,include
import specific
from generic.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('yuvan/',yuvan,name='yuvan'),
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path

app_name='sad'
urlpatterns=[
    path('oneside/',oneside,name='oneside'),
    path('commited/',commited,name='commited'),
    path('breakup/',breakup,name='breakup'),
    path('singles/',singles,name='singles'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def yuvan(request):
    return render (request,'yuvan.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def oneside(request):
    return render(request,'oneside.html')

def commited(request):
    return render(request,'commited.html')

def breakup(request):
    return render(request,'breakup.html')

def singles(request):
    return render(request,'singles.html')

templates/breakup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Breakup</title>
</head>
<body>
    <center>
        <h1>-><button><h2>BREAK UP</h2></button><-</h1>
          <h1>idhuvarai</h1>
        <h1>Illaatha unarvidhu</h1>
   <h1>Idhayathai thundaakkum ninaividhu</h1>
      <h1>Manadhinai mannodu</h1>
    <h1>Pudhaithidum pennai nambaathae</h1>
            <h1>Kaadhal endraal</h1>
         <h1>Athanaiyum kanavu</h1>
           <h1>Kann moodiyae</h1>
          <h1>Vaazhgindra uravu</h1>
           <h1>Pengal endraal</h1>
        <h1>Aanai kollum noiyaanathae</h1>
             <h1>Aiyyo intha</h1>
         <h1>Ilamaiyin thodakkam</h1>
          <h1>Indrae muttrupulli</h1>
         <h1>Adhai sollaamal solli</h1>
    <h1>Nammai paiththiyam aakkum</h1>
     <h1>Pennai thedi tholaiyaathae…</h1>
    </center>
    <center>
        <h2><a href="{% url 'yuvan' %}">Return yuvan</a></h2>
    </center>
</body>
</html>

templates/commited.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commited</title>
</head>
<body>
    <center>
        <h1>-><button><h2>COMMITED</h2></button><-</h1>
            <h1>Oore avala patha</h1>
        <h1>Ava enna mattum patha</h1>
      <h1>Yaar sonnalum namba maata</h1>
        <h1>Ava thaanda number keta</h1>
           <h1>Pasanga scene eh potta</h1>
        <h1>Ava kandukavae maata</h1>
          <h1>En kooda pecha pota</h1>
       <h1>Naan enna avalo smart ah</h1>
         <h1>Cute aana smile eh potu</h1>
              <h1>Saachitalae</h1>
        <h1>Kan jaada kaati enna</h1>
              <h1>Kouthitalae</h1>
       <h1>First ellam ozhunga ninnen</h1>
          <h1>Ennaadi enna panna</h1>
          <h1>Nidhaanam ippo illa</h1>
        <h1>Kaalum tharayil nikkavilla</h1>
          <h1>Saachitalae aala saachitalae</h1>
     <h1>Maathitalae vazhka maathitalae</h1>
        <h1>Saachitalae aala saachitalae</h1>
     <h1>Maathitalae vazhka maathitalae</h1>
             <h1>Aala saachitalae</h1>
        <h1>Vazhka maathitalae</h1>
          <h1>Aala saachitalae</h1>
         <h1>Vazhka maathitale...</h1>
    </center>
    <center>
       <h2><a href="{% url 'yuvan' %}">Return yuvan</a></h2>
    </center>
</body>
</html>

templates/oneside.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Oneside</title>
</head>
<body>
    <center>
        <h1>-><button><h2>ONE SIDE</h2></button><-</h1>
            <h1>Kaadhal vaithu</h1>
        <h1>Kaadhal vaithu kathirunthen</h1>
        <h1>Kaatril unthan kural mattum</h1>
            <h1>Kettirunthen</h1>
            <h1>Sirithai isai arinthen</h1>
        <h1>Nadanthai dhisai arinthen</h1>
          <h1>Kaadhal enum kadalukkul</h1>
           <h1>Naan vizhunthen</h1>
        <h1>Karaiyinil vantha pinnum</h1>
            <h1>Naan midhanthen</h1>
          <h1>Asainthai anbae asainthen</h1>
        <h1>Azhagai aiyo tholainthen</h1>
               <h1>Kaadhal vaithu</h1>
        <h1>Kaadhal vaithu kathirunthen</h1>
        <h1>Kaatril unthan kural mattum</h1>
            <h1>Kettirunthen</h1>
          <h1>Asainthai anbae asainthen</h1>
         <h1>Azhagai aiyo tholainthen</h1>
          <h1>Devathai kadhai kettapothellam</h1>
         <h1>Nijam endru ninaikkavillai</h1>
       <h1>Neril unnaiyaee… partha pinbu naan</h1>
         <h1>Nambi vitten marukkavillai</h1>
           <h1>Adhikalai vidivathellam</h1>
           <h1>Unnai parkkum mayakkathilthan</h1>
             <h1>Andhi malai maraivathellam</h1>
             <h1>Unnai partha kirakkathilthan...</h1>
    </center>
    <center>
        <h2><a href="{% url 'yuvan' %}">Return yuvan</a></h2>
    </center>
</body>
</html>

templates/singles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Singles</title>
</head>
<body>
    <center>
        <h2>-><button><h2>SINGLES</h2></button><-</h2>
           <h1>Aa….aaa…aa…</h1>
       <h1>Haa….aaa…aa….</h1>
       <h1>Vaazhkaiya yosingada….
    <h1>Thala ezhutha nalla vaasingada</h1>
        <h1>Yosichu paarungada</h1>
      <h1>Ellorum onna serungada</h1>
    <h1>Irukkura varaikkum anubavikka</h1>
        <h1>Ilamai yeththukkada</h1>
    <h1>Varugira varaikkum laabamada</h1>
      <h1>Vasathiya thedungada… go….</h1>
          <h1>Ini jalsa pannungada….</h1>
     <h1>Gujaala jilpa kaattungada</h1>
        <h1>Ini jalsa pannungada…</h1>
     <h1>Gujaala jilpa kaatungada</h1>
            <h1>Ahaan…….</h1>
     <h1>Gnyaabagam vanthathada….</h1>
<h1>Andha naal gnayaabagam vanthathada</h1>
     <h1>Nanbanai vida oruthan</h1>
     <h1>Lifekku thevai illaiyada</h1>
   <h1>Natpukku kooda karpugal undu</h1>
       <h1>Nalla therinjukkada</h1>
 <h1>Arputhamaana nanbargal serntha</h1>
     <h1>Vettrigal kumiyumada</h1>
    <h1>Nam vettrigal kumiyumada...</h1>
    </center>
    <center>
        <h2><a href="{% url 'yuvan' %}">Return yuvan</a></h2>
    </center>
</body>
</html>

templates/yuvan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GEN</title>
</head>
<body>
    <center>
        <h1>-><button><h2>YUVAN SHANKAR RAJA</h2></button><-</h1>
        <h3>All Time Favorite's...</h3>
    </center>
    <center>    
        <h2>-><u>One Side</u><-</h2>
        <h3><a href="{% url 'sad:oneside' %}">Kaadhal Vaithu</a></h3>
    </center>
    <center>
        <h2>-><u>Commited</u><-</h2>
        <h2><a href="{% url 'sad:commited' %}">Saachitale</a></h2>
    </center>
    <center>    
        <h2>-><u>BREAKUP</u><-</h2>
        <h2><a href="{% url 'sad:breakup' %}">idhuvarai</a></h2>
    </center>
    <center>    
        <h2>-><u>SINGLES</u><-</h2>
        <h2><a href="{% url 'sad:singles' %}">Vaazhkaiya yosingada</a></h2>
    </center>
</body>
</html>